Project NOT TODO
PhillipUg/not-todo-list pull request #2
Opened 2020-08-29 11:31 UTC by PhillipUg

### In this project we have done the following;
- used constructor function to create our objects
- used webpack to bundle out scripts
- used bootstrap for styling
- enabled users to create, read, delete and update todo items
- enabled users to create projects and add items under those projects

2020-08-29 12:47 UTC, uryelah requested changes
Hi **Safa Erden & Phillip Musiime**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with this project, the (not) Todo list works pretty well and the data persistent is working well.
There are some issues with the code organization that I address at the comments below, so make sure to read them carefully and remember to separate the DOM logic from Todo logic and to keep everything encapsulated inside modules and factory functions.

Check the pointers below and keep on coding! 🏃 💨 

# Required Changes 🏗️ 🐛 💡

- [x] [OPTIONAL] The edit feature is kind of confusing from the user standpoint.
Since you just change the action of the same form used for adding a todo it seems that nothing happened and it's not clear that clicking the '+' button will perform the edit and not create a new one.
Why don't you create an edit form, hide it, and show it when a user clicks edit on a todo?

- [x] The arrow buttons at the left and right of the screen are not doing anything, please remove them if they are not currently working/not have an event attached to them.

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-08-29 12:47 UTC, uryelah commented on package.json
> +    "start": "webpack-dev-server --mode development --open",
- [ ] Add `webpack-dev-server` to your dev dependencies. Otherwise one can't run this command after dowloading your code.

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +function render() {
- [ ] You have a file for the DOM manipulation that's empty, why don't you put this and other DOM related functions there?

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +function sideScroll(element, direction, speed, distance, step) {
- [ ] Move to the DOM file

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +  const scrolled = ul.scrollWidth - ul.scrollLeft === ul.clientWidth;
- [ ] Move to the DOM file

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +window.onload = render();
- [ ] Move to the DOM file

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +const closeBtns = document.querySelectorAll('.fa-times-circle');
- [ ] try to put this inside one of your modules/functions

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +const clickableLi = document.querySelectorAll('.list-group-item');
- [ ] Move to the DOM file

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +function showForm(item) {
- [ ] Move to the DOM file

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +function renderItems(result) {
- [ ] Move to the DOM file

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +const projecItmBtn = document.getElementById('projectItem');
- [ ] Move to the DOM file

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +function itemToggleListener() {
- [ ] Move to the DOM file

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +function updateItemStatus(itemId, itm) {
- [ ] Move to the DOM file

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +function editItems() {
- [ ] Move to the DOM file

2020-08-29 12:47 UTC, uryelah commented on webpack.config.js
> +module.exports = {
- [ ] Add the devserver output location so the `npm run start` command works on all systems.
```
  devServer: {
    publicPath: '/',
    contentBase: './dist',
    hot: true
}
```

2020-08-29 12:47 UTC, uryelah commented on README.md
> +# Project: Restaurant Page
- [ ] Please update this, this app is not the restaurant page.

2020-08-29 12:47 UTC, uryelah commented on README.md
> +<!-- ABOUT THE PROJECT -->
- [ ] Please uncomment and include the Instalation instructions to the readme.

2020-08-29 12:47 UTC, uryelah commented on src/index.js
> +const leftBtn = document.getElementById('slide-left');
- [ ] [ ] Let's try to put all these DOM selections in the file and DOM related functions inside a Dom Module in another file.
Read more about the module pattern [on the Odin project.](https://www.theodinproject.com/courses/javascript/lessons/factory-functions-and-the-module-pattern)

2020-08-31 10:52 UTC, PhillipUg commented
worked on issues raised by previous reviewer. Fixed linter errors.

2020-08-31 10:53 UTC, PhillipUg commented
worked on issues raised by previous reviewer. Fixed linter errors.

2020-08-31 11:36 UTC, rOluochKe approved these changes
Hello Team
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy hacking

2020-08-31 11:56 UTC, merged